### ISSUE TITLE
Performance Issues in Reason 9.5/10

### ISSUE THREAD

**Issue by Coirt** [mzuther/K-Meter#19]
I absolutely love K-Meter and would gladly pay if it was not a free plug-in. I have not seen any other meter that is so simply and elegant.

It causes Reason to click and pop when in a project though and I can not have it constantly in Reason I have to keep adding it to check levels. 

Is there any known issues with Reason or any plans to update?

**Comment by mzuther** [comment]
Which version did you try - 2.6.1 or 2.2.0?

**Comment by LKHSogpit** [comment]
I'm on version 2.6.1 
Sorry forgot to add that.

Windows 7 Pro 64bit

**Comment by mzuther** [comment]
I haven't got a clue why this happens and I also don't use Reason myself. Have you tried version 2.2.0? The code is mostly the same, it may just look a little different.

**Comment by LKHSogpit** [comment]
I'm going to try older builds. The only thing I can think of is the buffer size of K-Meter. Reason uses 64 for internal buffer to process real time audio. There is no way to change that it uses 64 for CV modulation. The clicks/pops are like buffer clicks/pops. Reason has got a changeable buffer size but it makes no difference what it is on because the internal is stuck on 64.

**Comment by mzuther** [comment]
This sound like a possible solution. I guess you can code, as you have just forked K-Meter. If this is the case, open "plugin_processor.cpp" and try to change lines 58 and 70 from "nTrakmeterBufferSize(1024)" to "nTrakmeterBufferSize(64)". K-Meter runs this way, although it does not match its specs.

Otherwise, please send me a private message with your email address and I'll send you a test build.

**Comment by LKHSogpit** [comment]
Oh okay Thanks. Actually just learning how to code very green! I'll try it if not successful I'll send you the pm.

**Comment by mzuther** [comment]
Hi Coirt,

this is just a short reminder that I haven't forgotten you.

I have just been able to reproduce the problem which is a first step in fixing the issue. I'm also fairly confident that I have a solution in mind, but as it is quite complicated, you will still need patience. Possibly a lot... :)

Best,

Martin

**Comment by Coirt** [comment]
No worries Martin, Thanks. Have not had a lot of time to produce lately, learning Java.

**Comment by mzuther** [comment]
Hi Coirt,

I have released K-Meter 2.8.0 which fixes the problem for me. Could you please try it and report back?

Thanks,

Martin

**Comment by mzuther** [comment]
No answer yet, so I consider this issue fixed.
