### ISSUE TITLE
K-Meter fetches JACK ports improperly

### ISSUE THREAD

**Issue by RomanHargrave** [mzuther/K-Meter#26]
### Describe the bug

When configuring K-Meter (standalone) for use with JACK, the list of 'outputs' appears to be a list of client output ports and the list of 'inputs' is a list of client input ports; however, selecting an 'output' does not connect the named client's output to K-Meters _input_ ports, but rather attempts to connect K-Meter's _output_ port to that client's (often non-existent) _input_ port.

Take the following image for example - 'system has both input _and_ output ports, so it appears in both input and output dropdowns.
![image](https://user-images.githubusercontent.com/6024227/88955240-433db680-d261-11ea-8a07-4b8c7e354736.png)

However, this problem becomes apparent when looking at the 'strawberry client'. This client _only_ has output ports, but is listed in the K-Meter output dropdown as opposed to the _input_ dropdown.
![image](https://user-images.githubusercontent.com/6024227/88955420-84ce6180-d261-11ea-877f-f7cc5d256145.png)

### Steps to reproduce

List *all* steps to reproduce the behavior:

1. Start K-Meter
2. Set device type to 'JACK'
3. Attempt to connect

### Expected behavior

'Output' and 'Input' client lists are swapped.

### Environment (please complete the following information)

 - OS: Gentoo x86_64
 - Plugin (not really a plugin): Precompiled K-Meter standalone for stereo (sha256: `5b021e3f007a04749774bd994b538e56b1656ffb92ba418ae8eb6c9ab9806cb2  kmeter_stereo_x64`)
 - JACK version: JACK2 v1.9.14 (`jackdmp version 1.9.14 tmpdir /dev/shm protocol 8`)

Did you compile K-Meter yourself? no, I don't want to deal with JUCE right now.

**Comment by mzuther** [comment]
Hi Roman,

thanks for your bug report! This behaviour is indeed weird...

Unfortunately, there is nothing that I can do about it. I simply use the standard JUCE stand-alone class. In my opinion, JUCE's JACK implementation is quite flawed. There are three things that you could do:

1. report this issue at [JUCE](https://github.com/juce-framework/JUCE) - the JUCE version is displayed when you start K-Meter in a terminal session

1. set input and output to unused ports and use QjackCtl or a similar application to connect K-Meter to the correct ports (this is what I do)

1. wait and hope that this was fixed in JUCE 6 (however, chances are small, and JUCE 6 has just been released, so I will wait until the end of the year before I update K-Meter)

Sorry I can't be of any help...

Martin

**Comment by RomanHargrave** [comment]
It had occurred to me that this could be JUCE related. I actually did attempt manual connection, but it didn't end well. It would be great if it were possible to disable autoconnect (I can at the server level, but don't want to), but again - JUCE.

I'll take this over there, and no worries. Thanks. I can always run this in a plugin host.
